### ISSUE TITLE
Network Key, Passphrase, Name

### ISSUE THREAD

**Issue by EinSoldiatGott** [SodaqMoja/SodaqOne-UniversalTracker-v3#2]
Hi

DEFAULT_APPSKEY_OR_APPEUI is the Network name? does it accept only EUI or Name also? 
DEFAULT_NWSKEY_OR_APPKEY is the Passphrase? Does it accept only key or passphrase also?

Does it expect hexadecimal values or string values? Or what's the expected format 

Thanks

**Comment by realrolfje** [comment]
Setting the APPEUI and APPKEY is described on the SODAQ ONE support site:
https://support.sodaq.com/sodaq-one/connect-to-the-things-network/

**Comment by EinSoldiatGott** [comment]
Thanks
